#![doc = include_str!("../README.md")]
pub(crate) mod cli;
pub mod error;
pub mod filtering;
pub mod identifiers;
pub mod io;
pub mod pipelines;
pub mod processing;
pub mod sources;
pub mod transformers;
